### ISSUE TITLE
Does not seem to work in latest React Native

### ISSUE THREAD

**Issue by nolanlawson** [tradle/asyncstorage-down#2]
I'm using React Native 0.11.0, Node 4.0.0, XCode 7.0, and iOS 9 in the iPhone Simulator.

Running a [demo app](https://github.com/nolanlawson/TestAsyncStorageDown) exactly as described in your README, I get 

![screenshot 2015-09-20 15 26 24](https://cloud.githubusercontent.com/assets/283842/9982473/f95bbba2-5fab-11e5-8a7e-c13fdf3936d9.png)

In the logs it says:

```
Unable to resolve module events from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/lib/levelup.js
Unable to resolve module util from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/lib/levelup.js
Unable to resolve module util from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/lib/levelup.js
Unable to resolve module util from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/node_modules/deferred-leveldown/deferred-leveldown.js
Unable to resolve module stream from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/readable.js
Unable to resolve module buffer from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js
Unable to resolve module events from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js
Unable to resolve module stream from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js
Unable to resolve module util from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js
Unable to resolve module buffer from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_writable.js
Unable to resolve module stream from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_writable.js
Unable to resolve module buffer from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/node_modules/string_decoder/index.js
Unable to resolve module util from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/lib/util.js
Unable to resolve module leveldown/package from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/lib/util.js
Unable to resolve module leveldown from /Users/nolan/workspace/TestAsyncStorageDown/node_modules/levelup/lib/util.js
```

Any advice? To repro, just open up that demo app in XCode and hit Run.

**Comment by mvayngrib** [comment]
@nolanlawson thx for reporting, haven't tested with 0.11.0 yet, will do tomorrow

**Comment by ntwcklng** [comment]
Maybe Node 4.0.0 is the problem? See:
https://github.com/facebook/react-native/issues/1758

**Comment by nolanlawson** [comment]
Hm, I'm still on npm 2.14.2. I'll try with node 0.12 though.

**Comment by nolanlawson** [comment]
Oh weird, the [React Native docs](https://facebook.github.io/react-native/docs/getting-started.html) now say they require Node 4.0 or above.

**Comment by mvayngrib** [comment]
@nolanlawson any luck? I won't able to get to this today, slammed, hopefully tomorrow

**Comment by mvayngrib** [comment]
@nolanlawson made some progress, got it working locally, but still haven't figured out exactly what it is that breaks it

**Comment by ghost** [comment]
Also running into this issue.  Looking forward to the resolution :)

**Comment by siuying** [comment]
I saw there is an update version last month, is `asyncstorage-down` working? if so, it would be grateful if @mvayngrib can advise how to setup to make it work...

**Comment by mvayngrib** [comment]
@siuying pushed an [example](https://github.com/mvayngrib/adexample). Sorry, don't have much bandwidth to spend on this, take a look at the postinstall script which hacks a bunch of things to make a node-like environment in react native. If you don't care about the size of your project and don't mind having all the node core shims, it can be simplified to rn-nodeify --install --hack

cc @bradynapier

**Comment by siuying** [comment]
@mvayngrib Thanks, this is a big help. Couldnt get pouchdb working yet, but got some real progress.
