### ISSUE TITLE
Is this library using leveldb behind the scenes or just wraps AsyncStorage?

### ISSUE THREAD

**Issue by DonManley** [tradle/asyncstorage-down#5]
It seems that this library uses AsyncStorage and not leveldb (which supports range queries, etc). Is this correct?

**Comment by mvayngrib** [comment]
wrapping AsyncStorage. rocksdb would be the one to wrap for a native leveldb backend. Some people have gotten rocksdb to work, e.g. see https://gist.github.com/chirag04/6dbe96a039d0bdfd31ec and https://github.com/facebook/react-native/issues/1892#issuecomment-174245078

**Comment by DonManley** [comment]
Thanks for the quick answer! Going a bit off topic, it's strange then that react's AsyncStorage does not expose any API to do a range query, a query between upper and lower key boundaries. The whole purpose of LevelDB is to provide range searches in O(log N). When retrieving one or all keys as AsyncStorage forces one to do, searching becomes at least O(n), which sort of defeats the purpose of using a BigTable-like NoSQL database to begin with, because database just becomes just a some form of a persistent hashtable. Perhaps, I'm missing something? I don't get why react-native supports RocksDb, but does not seem to expose at least one API function to do a range query.

**Comment by mvayngrib** [comment]
Yea, Ayncstorage API doesn't have range queries. React native actually
currently
doesn't support Rocksdb, but when they do, you're right, asyncstorage will
not really take advantage of its range queries. So it would be better to
just create a bridge module for Rocksdb, and then create a leveldown
wrapper for that module

On Sunday, June 5, 2016, DonManley notifications@github.com wrote:

> Thanks for the quick answer! Going a bit off topic, it's strange then that
> react's AsyncStorage does not expose any API to do a range query, a query
> between upper and lower key boundaries. The whole purpose of LevelDB is to
> provide range searches in O(log N). When retrieving one or all keys as
> AsyncStorage forces one to do, searching becomes at least O(n), which sort
> of defeats the purpose of using a BigTable-like NoSQL database to begin
> with, because database just becomes just a some form of a persistent
> hashtable. Perhaps, I'm missing something? I don't get why react-native
> supports RocksDb, but does not seem to expose at least one API function to
> do a range query.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/tradle/asyncstorage-down/issues/5#issuecomment-223835568,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAFH7G9AHH5v8TnfxjTUUGQ6UsRxgeA6ks5qIzEIgaJpZM4IubbS
> .

## 

Mark Vayngrib
CTO & Co-founder
http://tradle.io
UK: +44 (0)7490 453346
US: +1 (201) 925-6626
